spring.application.name=kosmo163_boot

server.port=80

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp


# DB 연결 정보
# ip:port
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
# id
spring.datasource.hikari.username=cns
# pw
spring.datasource.hikari.password=cns
# DB JDBC 정보
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

# Mybatis 설정 정보
# config의 typeAlias대체
# 같은 class명이 존재하면 에러 발생
mybatis.type-aliases-package=com.semin.app

mybatis.configuration.map-underscore-to-camel-case=true